### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by helfy18** [SENG-499-Company2-B01/Algs1#52]
- [x] Switch num_seats from classroom to course 
- [x] filter classes to remove not current semester
- [x] pass json from views to newcso.py
- [x] remove file opens

**Comment by helfy18** [comment]
also, backend switched the users[].unavailable to users[].available
